language: perl

sudo: false

notifications:
  email: false

cache:
  directories:
    - ~/perl5

env:
  SPLIT_BUILD=0

perl:
#  - "5.10"
#  - "5.12"
#  - "5.14"
#  - "5.16"
#  - "5.18"
#  - "5.20"
#  - "5.22"
#  - "5.24"
#  - "5.26"
#  - "5.26-shrplib"

#before_install:
#  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules

script:
  - perl Makefile.PL
  - cpanm --notest --self-contained --installdeps .
  - make
  - prove -lmv -j1 t
