language: perl

sudo: false

notifications:
  email: false

cache:
  directories:
    - /home/travis/perl5

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.26-thr"
  - "5.28"

matrix:
  include:
    - perl: 5.26
      env: COVERAGE=1

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - coverage-setup

script:
  - perl Makefile.PL && make
  - prove -lm -j$(test-jobs) $(test-files) || prove -lmv $(test-files)

after_success:
  - coverage-report
