language: perl

sudo: false

notifications:
  email: false

cache:
  directories:
    - ~/perl5

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.26-thr"
  - "5.28"

matrix:
  include:
    - perl: 5.26
      env: COVERAGE=1

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command

install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled

before_script:
  - coverage-setup

script:
  - prove -l -j$(test-jobs) $(test-files)   # parallel testing

after_success:
  - coverage-report
