language: perl

sudo: false

notifications:
  email: false

cache:
  directories:
    - /home/travis/perl5

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.26-thr"
  - "5.28"

install:
  - perl -v
  - cpanm --quiet --notest Dist::Zilla
  - dzil authordeps --missing | cpanm --notest --quiet
  - dzil listdeps   --missing | cpanm --notest --quiet

script:
  - dzil test -j 4
